name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-newrelic-php-agent:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            axelpal/newrelic-php-agent
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push newrelic-php-agent
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GIT_BRANCH_OR_TAG=${{ env.GITHUB_REF_NAME }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile
          platforms: "linux/amd64,linux/arm64/v8"